# Generated by Django 3.1.7 on 2021-03-19 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20210319_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_stat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 14, 42, 1, 256986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 14, 42, 1, 256424, tzinfo=utc)),
        ),
    ]
