# Generated by Django 3.1.7 on 2021-03-19 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20210319_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 14, 46, 4, 290207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 14, 46, 4, 289702, tzinfo=utc)),
        ),
    ]
